README.md
lib/language.js
lib/number.js
test/number.js

This pull request adds the number.multiple() validation option as mentioned in this issue: https://github.com/hapijs/joi/issues/532.
(I saw this tagged under new contributors on http://hapijs.com/contribute)

added number.multiple()

---

README.md

As a contribution for improving the documentation for beginners (https://github.com/hapijs/joi/issues/713) 
I am adding information regarding the usage of {}, Joi.object({}) and Joi.object().keys()

Additional clarification for beginners - README.md

---

API.md
lib/array.js
lib/language.js
test/array.js
test/errors.js

Feel free to ping me for suggestion/feedback on my code. Happy to change them if necessary.
closes #659

Toggable ordered flag for array to match items against input in order

---

lib/any.js
test/any.js

Addresses #773 for node-0.x. Backport of #774.

Fix any.default() returns default object reference

---

API.md

Update Api documentation to comply the es6 new style.

Updated doc

---

test/string.js

More tests for IPv6

---

API.md

[https://github.com/hapijs/joi/blob/master/API.md#-notation](https://github.com/hapijs/joi/blob/master/API.md#-notation)

Fix: `schema` can't call `validate()` method

---

API.md
lib/any.js
lib/index.js
lib/language.js
lib/object.js
package.json
test/function.js
test/index.js

Add synchronous extensibility

---

API.md

Added note about null in docs

---

API.md

Fix variable name in documentation

---

lib/errors.js

Fixes #1006
Added option for the color coding in `error.annotate`. Hope I did it
right.

Added option for the color codeing in error.annotate

---

API.md

fixed string maxArity documentation

---

lib/any.js

Per discussion on https://github.com/hapijs/joi/pull/998

Clean up any.valid code

---

lib/index.js
test/index.js

#1201 - setup can return joi object to replace origin schema

---

lib/types/any/index.js
test/types/any.js

remove empty flag if only reset is used

---

lib/types/any/index.js
test/types/any.js

Remove validation from .example

---

API.md

Took me a while before I figured that out myself.

doc: clarify array().single() behavior

---

lib/types/object/index.js

This cleans up the logic a bit. The performance is probably about the same, though I haven't benchmarked it.

Use Set() for handling of unprocessed keys

---

API.md
lib/types/string/index.js
test/types/string.js

Add enabled flag to string.trim()

---

API.md
lib/ref.js
lib/set.js
lib/types/alternatives/index.js
lib/types/any/index.js
lib/types/array/index.js
lib/types/date/index.js
lib/types/number/index.js
lib/types/string/index.js
test/types/alternatives.js

I should have done this when I created references.

Support self references. Closes #1569

---

lib/errors.js
lib/types/alternatives/index.js
lib/types/any/index.js
lib/types/date/index.js
package.json
test/set.js
test/types/alternatives.js
test/types/any.js
test/types/binary.js
test/types/lazy.js
test/types/object.js

+45% on `Schema creation` benchmark FWIW.

Bump to lab@18. Fixes #1653.

---

API.md
lib/errors.js
lib/index.js
test/index.js

See https://github.com/hapijs/joi/issues/1244

Throw typed ValidationErrors

---

README.md

Using @hueniverse 's proposed wording from #1636

Remove whitelist/blacklist terms

---

API.md

Add example for `when()` to express complex logic

---

README.md

fix(url): fix broken url in readme.md

---

lib/types/string/index.js

solved issue #1700 base64 validation returns RangeError

Resolved issue of maximum call stack exceeded

---

README.md

Change from `npm install --save joi` to `npm install --save @hapi/joi`

Change npm install command

---

README.md

minDomainAtoms is not supported in 15.0 update README example accordingly

update README with minDomainSegments 

---

API.md

Clarify referenced parameter resolution

---

lib/types/number.js
test/types/number.js

Fix for [#1876](https://github.com/hapijs/joi/issues/1876)

Fix: Exponential decimal #1876

---

lib/types/string/index.js
test/types/string.js

String multiple email address

---

API.md

Fix extend() redirection. Closes #2137.

---

API.md

Fix one instance of `valid()` call

---

API.md

Fix docs for advanced functions

---

lib/manifest.js
test/manifest.js

fix: describe() on schema with default value null

---

API.md

Hi Eran, 
Here's the fix for #2193
Uses fix suggested here: https://github.com/hapijs/joi/issues/2193#issuecomment-560497653
Please let me know if you want any further changes.

Minimal fix for #2193

---

API.md

Small tweak to fix documentation

Fix example joi extension

---

API.md
lib/validator.js
test/validator.js

Expose prefs in external()

---

lib/types/keys.js
test/types/object.js

Fix confusing message when refs are passed

---

lib/index.d.ts

Remove incorrect errors type

---

lib/index.d.ts
package.json

That fixed my initial issue #2555

fix: any.when() options parameters not supported as Array in index.d.ts

---

lib/types/keys.js
test/types/object.js

fix for stripUnknown not working for nested object on invalid object

---

lib/types/alternatives.js
test/types/alternatives.js

merge the results of a .match('all') if all the subschemas are objects

---

lib/types/alternatives.js
test/types/alternatives.js

merge subschema matches when subchemas are objects, or alternatives of objects

---

lib/index.d.ts

In TS typedef validateAsync return type Promise<any> instead of Promise<TSchema>

Fix validateAsync return type

---

package.json
test/types/string.js

Reverts hapijs/joi#2749
This only broke the tests without fixing the actual problem.

Revert "fixed typo"

---

lib/index.d.ts
test/index.ts

Fixes #2764 
#2785 which fixes same issue seems to be stuck for month after request to add test case. So I am opening this one, with both issue fix and test case, protecting from future degradation.

fix(d.ts): allow nested object schema for strictly typed object

---

lib/index.d.ts

Add artifact to typings.

---

lib/index.d.ts
test/index.ts

Supersedes #2835. Part of #2622.

types: support strict alternatives

---

lib/index.d.ts
test/index.ts

fix: allow all schema types to be defined and inferred

---

benchmarks/package.json
browser/tests/index.js
lib/types/string.js

fix: properly transform domain

---

API.md

chore: fix wrong usage of Joi.expression

---

lib/index.d.ts
test/index.ts

fix: validation warning types

---

lib/index.d.ts

#2963 make return value of validate match type definitions

---

lib/index.d.ts
test/index.ts

feat: Improve array().items type

---

API.md
lib/index.d.ts

* updated TypeScript definitions
* updated documentation
This PR fixed issue #2874.

Fix for #2874

---

lib/types/string.js
package.json
test/types/string.js

fix: domain default tld validation

---

lib/errors.js
test/errors.js

fix: label false should also hide explicit labels

---

API.md
lib/base.js
lib/index.d.ts
lib/types/alternatives.js
lib/types/array.js
lib/types/keys.js
test/isAsync.js

Adding a helper to facilitate work on #3080.

feat: add isAsync() helper
