README.md
Adding a clarifying statement that values whitelisted by `.allowed()` are not exclusively valid.
It was my own fault for not being familiar enough with the API, but this bit me as a result of assuming that "whitelisted" in the description implied that any not-whitelisted values would be considered invalid. I'm just submitting this to help anyone else who reads this in the same way.
=> Clarify documentation of any.allowed()

README.md, lib/any.js, lib/language.js, test/any.js, test/index.js
This covers the use cases of `Date.now`, UUID generation, and other similar methods.
=> allow passing a method to .default(), for #363

README.md, lib/any.js, lib/array.js, lib/object.js, test/any.js, test/array.js, test/object.js
=> add any.strip for objects and arrays

README.md
Found some dangling references to `includes()`.
=> Remove deprecated `includes` references, replace them with `items`.

lib/any.js, test/any.js
The validation would throw when using `presence` and another key because `values` would keep the values from the `presence` key in it thus not validating other keys.
Fixes #601
=> Validate multiple options with presence key in it

README.md, lib/object.js, test/object.js
Add a flag to ignore a missing key when renaming it.
```js
var schema = Joi.object().rename('b', 'a', { ignoreUndefined: true });
var input = {
a: 'something'
};
schema.validate(input, function (err, value) {
// input : {a: 'something'}
});
```
close #614
=> Add ignoreUndefined flag for rename()

lib/date.js, lib/number.js, lib/string.js, test/date.js, test/number.js, test/string.js
Invoking the following methods:
- number: min, max, less and greater
- string: min, max and length
- data: max and min
with e.g. Joi.ref('$a') causes the error: `Cannot read property 'context' of undefined` at lib/ref.js:19:256
The validation options where not being passed to the ref validation function, so only normal refs were working, but not context refs.
=> Fix allowing context refs on some string, number and date methods

README.md, lib/string.js, test/string.js
This is an implementation of the request made at hapijs/joi#648
I have added the `string.normalize()` function (basically inspired by `trim()`) following the name XSLT/XPath/XQuery gave to it (I was in doubt whether to call this `normalizeSpace()` or `normalize_space()`, but it seems JOI prefers shorter names).
I'm always baffled by `normalise` vs. `normalize`... I guess I'll go with the latter (again, XSLT/XPath/XQuery...)
=> Implementation of white space normalisation.

README.md, lib/any.js, test/any.js
This option enables you to validate your data without applying default values into it.
Can be usefull when your default values are dynamic.
Corresponding issue: https://github.com/hapijs/joi/issues/682
=> Add the "noDefaults" option

lib/errors.js, lib/object.js, test/errors.js, test/index.js, test/object.js
While working on building a custom error message formatter for Joi validation errors, I noticed an inconsistency with the `path` attribute of unknown object keys. Nested object keys don't have the full path. For example:
```js
Joi.validate({ key: 'value' }, {}, function (err) {
console.log(err.details[0].path); // prints "key"
});
Joi.validate({ key: { nestedKey: 'value' } }, { key: {} }, function (err) {
console.log(err.details[0].path); // prints "key" instead of "key.nestedKey"
});
```
This patch adds the full path to validation errors of unknown nested keys.
=> fix unknown nested key path

lib/object.js, test/object.js
I noticed that the `path` on failing `or` validators has a trailing `.` which I believe is incorrect. This fixes that.
=> removes trailing "." from or path

test/object.js
It turns out that I didn't manage to reproduce the issue reported in #693, and I believe that the error must lie in an external error. Nevertheless, I thought it would be good to add a test for this as to prevent it from happening in the future.
=> test: prototype-less objects

package.json
joi isn't coming up in https://hapi-plugins.com/ results because `hapi` isn't in the keywords.
=> add hapi to package.json keywords so joi is searchable

package.json
As [npm 3](https://github.com/npm/npm/releases/tag/v3.2.1) is out (still in beta though).
I don't see why not support it in package.json.
=> allow npm 3 in package.json engines entry

README.md, lib/index.js, test/index.js
* When Joi.assert doesn't throw, return the valid value.
=> add attempt function

lib/object.js, test/object.js
Small bug fix for the `path` returned in the details when unknown keys are not allowed at the root level. The path contained a leading `.` that was not necessary.
Related to #690 and #684.
=> removes leading "." from path at root object level

lib/any.js, test/any.js
Addresses https://github.com/hapijs/joi/issues/773.
=> Fix any.default() returns default object reference

API.md, lib/language.js, lib/object.js, test/function.js
add a predicate to enfore number args should take provided function.
This is fully functional, but predicate for min/max should be added to.
Waiting for some feedback for this implementation, (and suggestion for name. (so far thinking about `maxArity`, `minArity`
=> Add a arity predicate for functions

API.md, examples/timestamps.js, lib/date.js, lib/language.js, test/date.js
_Revised_
--
This PR includes the following changes:
- Support for decimals in `date()` validation
- New constraint for `date.timestamp()` that supports both _javascript_ and _unix_ timestamps
- Updated Tests, API documentation, and added date example
_Note: Because javascript timestamps are millisecond-based and unix timestamps are second-based, the `timestamp()` constraint accepts an optional `type` parameter to ensure proper date conversion for the given input value._
closes #789
=> Date enhancements and support for Unix Timestamps

generate-readme-toc.js, package.json
Currently, the _API Reference_ link in the README takes users to `master`. This is ok most of the time, but when master has been updated but not yet published users are taken to documentation that does not match the current version.
This Pull Request updates the toc generator script to also version the _API Reference_ link in the README.
_…as well as uses ES6 template strings._
=> Generate versioned API Reference link in README

API.md
There was a typo. This fixes it. Simple.
=> Fix typo in string.max docs

API.md
This changes `const` to `let` in code blocks where re-assigns were being made to constants (hope I didn't miss any).
Code blocks where multiple constants named `schema` are being declared are also invalid but I guess those are to remain as-is for illustration purposes and not be used in real life.
=> Do not re-assign to constants

API.md, lib/boolean.js, test/boolean.js
We would like to be able to send 1 as a truthy value and 0 as a falsy value, as our back end uses MySQL which stores booleans as 1s and 0s.
=> Allow 1 to be true and 0 to be false.

lib/index.js, test/index.js
This creates a custom Joi from an instance of the Any class instead of from an empty object. This allows the custom Joi to retain the properties and functions available on the original Joi object such as `.when` and `.disallow`.
This closes #933
=> Fix missing top-level methods

API.md, lib/string.js, test/string.js
Adds UUID version 1 through 5 support.  Based on #970.
=> Adds UUID Support

API.md, lib/any.js, lib/boolean.js, lib/set.js, test/any.js, test/boolean.js
This commit resolves #991 by adding the following support:
- Implements `Joi.boolean().truthy()` and `Joi.boolean().falsy()`
- Both methods accept either a string, or an array of strings.
- Both methods utilize `Hoek.assert` to ensure that the values passed are strings.
- Both methods have 100% test coverage.
- Both methods are documented in API.md.
=> Add support for truthy/falsy boolean values

lib/any.js, lib/object.js, test/index.js, test/object.js
For the `object.renames()` API, it currently stores data within the scoping of `schema._inner.renames`.  This set of schema definition is not projected within the `any.describe()` function.  I'm adding this with the intent that `renames()` meta data can be part of a common contract.  This will also help support [felicity](https://github.com/xogroup/felicity).
Please let me know of any concern with this implementation.
This is also a fix to Issue #1026
=> Extending describe() to include renames in metadata

API.md, lib/language.js, lib/string.js, test/string.js
Just like [string.hex()](https://github.com/hapijs/joi/blob/v9.2.0/API.md#stringhex) but for base64
=> Added a string.base64() method.

lib/any.js, lib/object.js, test/helper.js, test/object.js
For the API `object.type()`.  I'm extending the meta data storage of the constructor within the schema to be placed in `options`.  Also extending `any.describe()` to project it to a new item schema within the `rules` array.  This will help facilitate an object generation of the exact type specified by this API contract.  Problem right now is that the type is translated to a `name` of type `String` and the ability to reproduce via `Object.create()` is lost since there is no way to cast it back to the original reference.  Support is being added within [felicity](https://github.com/xogroup/felicity)  
Let me know if there is a better way of implementing this.
**Using the Joi API**
```Javascript
Joi.object().type(RegExp);
```
**Storage within the schema**
```Javascript
{
_test: [{
name: …
```
=> Extend describe() for type

API.md, lib/language.js, lib/string.js, test/string.js
Per discussions in #1033 and #1020, refactored `string().regex(pattern, [name])` to support `string().regex(pattern, [name | config])` as follows:
1. If `name` is a string it behaves as currently implemented. No change.
2. If `config` is an object, it supports the following properties:
- `name`: {string}, behaves as currently implemented.
- `invalidate`: {boolean}, defaults to `false` behavior; if `true`, disallows the provided regex pattern.
Usage: 
```Javascript
const schema = Joi.string().regex(/[a-z]/, {
name      : 'lowercase',
invalidate: true
});
schema.validate('bad', (err, value) => {
if (err) {
// ValidationError: "value" with value "bad" matches the invalidated lowercase pattern
}
});
schema.validate('BAD', (err, value) => {
if (err) {} // err === null
});
schema.describe();
/* …
```
=> Implement String.regex "invalidate" configuration

API.md
Updating documentation to include `option.relativeOnly` flag for `string.uri()` API.
=> updated documentation for string.uri and relativeOnly flag

lib/index.js, test/any.js, test/array.js, test/binary.js, test/boolean.js, test/date.js, test/function.js, test/number.js, test/string.js
solution: throw an error when argument is passed in types that don't needed.
example: `Joi.string('argument') => throws 'Joi.string() does not allow arguments.'`
issue: https://github.com/hapijs/joi/issues/1009
=> adding validation for unnecessary arguments in primary types.

API.md
Removes v10.x deprecated `Joi.date().format()` syntax from API.md example, per #1063.
=> Update API.md to remove deprecated date.format syntax from an example

API.md
The examples in the documentation for `string.regex` didn't really validate what they were proposing to.
For example, `regex(/[0-9]/)` doesn't validate `alpha`, but it does validate `alpha1`, `numb3r`, `d00d`, etc. because it will match any strings that contain at least one number. `regex(/^[0-9]+$/)` however will only validate strings strings consisting entirely of numbers.
Similarly, `regex(/[a-z]/)` will validate `lowercase`, but it will also validate `LowerCase`, `Lowercase`, `LOWERCASe`, etc. because it will match any strings that contain at least one lowercase letter. `regex(/^[a-z]+$/)` however will only validate strings consisting entirely of lowercase letters.
=> Update `string.regex` examples

lib/index.js, test/index.js
I found it surprising while making an extension that the defaults I set in the params validation weren't being applied.
=> allow param defaults to be set by the param validations

README.md
Most people wouldn't want to do validation with callbacks as that adds unnecessary complexity to program flow.
See https://github.com/hapijs/joi/pull/636#issuecomment-248423449
=> Change Joi.validate examples to just return a value

API.md
This PR just brings a few updates to the current documentation to provide some insight on how `convert` works by default for each of the major types that `Joi` supports. 
Fixes #1098
=> Add Docs for `convert` functionality with types

README.md
Without cluttering up the README.md and keeping it as minimal as possible, added clarification that the callback is executed synchronously. This matches what is included in API.md and makes it clearer to new users without having to dig through the API docs or archived issues (#636) that there is no performance benefit of passing in a callback to validate, as typical node users would expect when such a callback option is provided.
=> (docs) Improve README with clarification on callbacks (#636)

lib/errors.js, test/errors.js, test/index.js
Fixes `TypeError: Cannot assign to read only property '_$miss$_forbiddenKey|1_$end$_'`
when a parameter is given as a JSON string with incorrect property.
=> Fix #964 Joi wrong value parsing

API.md
The schema object can be a joi type object or a plain object.
=> Update the API documentation of attempt and assert

API.md
schema.validate() is available in [any.js#L659](https://github.com/hapijs/joi/blob/master/lib/any.js#L659) but not in the document.
=> Add missing documentation for any.validate() in API.md

lib/alternatives.js, lib/any.js, test/any.js, test/index.js, test/ref.js
Adds the options set by `Joi.any().options({})` to the output from `.describe()`, per #1130 
```js
Joi.any().options({ abortEarly: false, convert: false }).describe()
// { type: 'any' }
```
```js
Joi.any().options({ abortEarly: false, convert: false }).describe()
// { type: 'any', options: { abortEarly: false, convert: false } }
```
=> Add "options" to describe output

lib/alternatives.js, test/alternatives.js
Addresses #1151 .
When a `.when()` has only an `otherwise`, subsequent `when()`s should now be checked until either a `then` is found or the last condition is reached.
```js
const schema = Joi.object({
a: Joi.number(),
b: Joi.number(),
c: Joi.number()
.when('a', { is: 1, otherwise: Joi.number().min(1) })
.when('b', { is: 1, then: Joi.number().min(1) })
});
schema.validate({
a: 1,
b: 1,
c: 0
}); // { error: null, value: { a: 1, b: 1, c: 0 } }
```
```js
const schema = Joi.object({
a: Joi.number(),
b: Joi.number(),
c: Joi.number()
.when('a', { is: 1, otherwise: Joi.number().min(1) })
.when('b', { is: 1, then: Joi.number().min(1) })
});
schema.validate({
a: 1,
b: 1,
c: 0
}); // child "c" fails because ["c" must be larger than or equal to 1]
```
=> Alternatives respect subsequent "when"s if first has only "otherwise"

lib/object.js, test/any.js
This will allow very interesting modular systems where you can define a global very generic object where all keys are optional. Then each module can add their own restrictions using that base object, allowing, disallowing or making required certain properties. Combine this with some default values and you will have a very strong and modular system with high consistency on the results.
=> add forbiddenKeys method to object

lib/types/string/index.js
This will allow dropping isemail dependency in hapi core.
=> Make isemail an optional dependency

API.md, lib/language.js, lib/types/array/index.js, test/types/array.js
This PR adds the ability for a user to use a reference for `array().length()`, `array().min()` and `array().max()` as well as adding test cases and documentation around the functionality.
Fixes #1017
=> Added the ability to use a reference for Array min/max/length

lib/types/string/index.js
This PR includes some performance improvements to the run-time validation of the `string().guid()` validation type. 
I ran a [series of benchmarks](https://github.com/DavidTPate/joi-bench/blob/dabe172db0e2aa81f43ea86b0381a2d4f11e7e02/benchmarks/string.js#L135-L158) for some common cases of GUID/UUIDs and then made tweaks to improve the performance.
**Schemas**
```js
const guidSchema = stringSchema.guid();
const guidVersionsSchema = stringSchema.guid({
version: ['uuidv1', 'uuidv2', 'uuidv3', 'uuidv4']
});
```
**Benchmarks**
```js
// validate-schema#guid
guidSchema.validate('D1A5279D-B27D-4CD4-A05E-EFDD53D08E8D');
// validate-schema#guid-wrapped
guidSchema.validate('{D1A5279D-B27D-4CD4-A05E-EFDD53D08E8D}');
// validate-schema#guid-versions …
```
=> Performance Improvements for string().guid()

package.json, test/types/string.js
`isemail` [v3.0.0](https://github.com/hapijs/isemail/releases/tag/v3.0.0) has been released, adding support for unicode emails and removing DNS lookups entirely.
=> Update isemail from 2.x.x to 3.x.x

lib/types/string/index.js, lib/types/string/ip.js, lib/types/string/rfc3986.js, test/types/string.js
Fix how we handle CIDRs for IPv6 so that we are allowing up to 128 for the CIDR.
Fixes #1232
=> Fix Value Range for IPv6 CIDRs

API.md, lib/types/string/index.js, test/types/string.js
Allow passing an option to string().isoDate() which formats the string as the simplified extended ISO format
Mimics the formatting returned by date().iso(), and the default ensures backwards compatibility.
ideally would use convert option to toggle whether the conversion happens, but since convert defaults to true, this would be a breaking change.
Closes #1196
=> Allow passing an option to string().isoDate()

API.md
Adds `exist`, an undocumented alias of required
=> Add exist to API.md

API.md, lib/cast.js, lib/index.js, lib/types/alternatives/index.js, lib/types/any/index.js, lib/types/array/index.js, lib/types/object/index.js, test/index.js
Here's a feature that has been requested previously (sorry can't find the issues) and I've been thinking about how to expose it, so this PR is my proposal. Let me know what you think.
~I know accessing the `_type` is meh, but I doubt it will change and doing `schema instanceof Joi.object().constructor` is a bit tedious. Maybe type could be exposed through a getter...~
=> Add `Joi.defaults()`

API.md, lib/language.js, lib/types/any/index.js, lib/types/string/index.js, test/types/string.js
Implements #1289, I did have some time after all 😄
=> Add string.normalize for unicode normalization

API.md, lib/types/any/index.js, test/index.js, test/types/any.js
Let me know if it fits your goals @hueniverse.
=> Add promise-like API to validate. Fixes #1314.

lib/language.js, lib/types/func/index.js, test/types/function.js
- Add Joi.func().class()
- Ensure a `function` is not valid against `Joi.func().class()`
- Ensure a `class` is valid against `Joi.func().class()`
=> Add Joi.func().class()

API.md, lib/types/object/index.js, test/index.js, test/types/object.js
This PR extends `Joi.object.rename()` to allow the renaming of key properties via regex. The necessity arose from needing to validate against url query parameters and being case insensitive, while still being able to refer to the param in question in my src code in it's default, expected format.
**Use case:**
client requests...
`base_url/resource?marketCode=191` - camel cased
`base_url/resource?marketcode=191` - lower cased
`base_url/resource?MarketCode=191` - pascal cased
```js
/*...assuming your use case is for api development with hapi, in your handler func you'd be able to reference marketcode in it's format specified in your validation schema */
const marketCodeRegExp = /^marketcode$/i;
config: {
validate: Joi.object().keys({
marketCode: Joi.string()
}).rename(marketCodeRegExp, …
```
=> Fixes [#1239]

API.md
As seen in https://github.com/hapijs/joi/issues/1274#issuecomment-335895009 - the date default example in the documentation causes bugs if you're expecting the current time, not the time that the process was started.
=> Fix #1274: Updated API documentation for default dates.

API.md
**Changelogs**
Fix simple typo `is` -> `if` in two places
=> Fix typo in string.min & string.length docs

lib/types/object/index.js, test/types/object.js
When using `Joi.object().pattern(...)` it is currently not possible to convert values to `undefined`.
I guess the provided test case is self explaining. If not, I am happy to provide a more detailed explanation.
=> Fix object pattern in combination with empty

lib/types/object/index.js, test/types/object.js
How does this look?
The assertion is for arguments.length === 2 rather than arguments.length <= 2 like you suggested ([extra arguments](https://github.com/hapijs/joi/pull/1394#issuecomment-356991804)).
=> Asserts that two arguments are provided to object.with() and object.without()

API.md
Change ```Lunh Algorithm``` to  ```Luhn Algorithm```
FIX #1417
=> Fix Api Reference Typo (Lunh)

lib/types/any/index.js, test/types/any.js
This fixes `any.valid()` and `any.invalid()` for `typeof === 'object'` values when used through a method that clones the schema.
=> Fix cloned valid() / invalid() object values

API.md, lib/index.js, test/index.js
Fixed the issue: #1383
This changed the path parameter of `Joi.reach` from string to array of strings
=> Changed a separator for path parameter to pre-split array approach for Joi.reach

lib/types/any/index.js
This speeds of validation of simple schemas by ~10x.
=> Avoid redundant copies of settings

lib/set.js, test/ref.js, test/types/any.js, test/types/string.js
Along with a `isSimpleValue` optimisation, this provides a 1000x speedup for the case in #1409.
=> Use Set() for internal Set backend

lib/language.js, lib/types/string/index.js, test/types/string.js
In most cases you probably want to create a byte-based representation from the hex string.
This PR adds a new `byteAligned` option, which will fail the validation when eg. `new Buffer(value, 'hex')` would fail due to bad alignment.
Due to semver, the option is considered `false` by default, preserving the existing behavior in all cases. I would probably switch this to `true` by default, when possible.
=> Add byteAligned option to hex string

API.md, lib/language.js, lib/types/date/index.js, test/types/date.js
=> add date greater less rules

lib/schemas.js
=> remove indirect require reference to index.js

API.md, lib/types/object/index.js, test/types/object.js
I saw this issue: https://github.com/hapijs/joi/issues/1382 and thought I might take a shot at it. It adds dynamicKeys to support validating object keys with schema instead of requiring a regex parameter. It also reworks pattern to just use dynamicKeys under the hood, but that might not be a great thing to stick with if there is a large performance gain in testing a single regex vs a schema that has a single regex rule.
~~As part of this, I also updated describe, but cannot for the life of me figure out how to make the describe test pass. Based on the output, the actual and expected describe results are identical, but the test still fails.~~ edit: I just had to sleep on it, found and fixed.
Anyway, I hope this helps or at least gives some folks ideas on how they might want to make this …
=> Allow object keys to be verified by schema

API.md, lib/types/array/index.js, test/types/array.js
Add the optional second param to array.unique, per the discuss in #1498 .
I named the param `configs` to avoid shadowing the already-defined `options` param in the test callback. Let me know if you prefer some other param name.
=> Add optional "config" param to array.unique for ignoreUndefined. Closes #1498

lib/types/string/rfc3986.js, test/types/string.js
Allow square braces in URL validation
Update regex to accept square braces
```
const Joi = require('./');
const schema = Joi.object().keys({
url: Joi.string().uri()
});
const resOne = Joi.validate({url: 'https://example.com?abc[]=123&abc[]=456'}, schema);
```
the snippet above wouldn't result in error because it's a valid URL with query.
Fixes [Issue: 1461](https://github.com/hapijs/joi/issues/1461)
=> Allow square braces in URL validation

API.md, lib/language.js, lib/types/string/index.js, test/types/string.js
Hi there!
Maybe you'll find this completely useless, or, I hope, useful, but in many of my projects, I use the data URI format to send pictures between my clients and my APIs.
This format is not so simple to validate, and just a regex is not sufficient. This is why I propose to add this validation: `string().dataUri()`.
I do not now what order may be the best, so I put it just near the `base64` as the use may be for some people quite the same.
Do not hesitate if you have any questions!
Thank you!
=> Data uri validation

README.md
Following discussion in the issue #1366 I thought it might be helpful to alter the README.md example that uses the `email` validation method to include `minDomainAtoms` as a way to signpost that the default RFC compliant options might not be what most are after.
Appreciate the maintainers may not agree with this in which case feel free to close.
Also thanks for the code, great library 👍
=> Highlight the minDomainAtoms option for the email validation method in readme

lib/index.js, lib/language.js, lib/types/symbol/index.js, test/types/symbol.js
For #1420. Let me know what you think.
=> Add symbol() type

API.md, lib/language.js, lib/types/array/index.js, test/types/array.js
See #1656 for use case.
@Marsup recommended creating an `array().includes()` method, but Joi already has an "includes" concept for arrays via `array().items()` and it's associated error messages. The target functionality more closely resembles `object().assert()`, except for array items, and as a supplement to `array().items()`.
`array().assertItem()` felt the most self explanatory. Feedback welcome.
=> Add array().assertItem(). Closes #1656

API.md
This pull request fixes a small typo in the API docs.
=> Fix typo: non -> none

package.json
Restores the `homepage` property to `package.json`. This property is required for the correct operation of hapitoc's documentation generation as per #1773.
**Changes**
- `package.json`- Restore the `homepage` property
_No test changes required_
=> Fix hapitoc 'API Reference' link generation in README.md

benchmarks/suite.js, lib/types/array/index.js, lib/types/binary/index.js, lib/types/object/index.js, test/types/array.js, test/types/object.js
This patch speeds up object and array string conversions for the type of invalid inputs that are likely in an `alternatives()` schema. On my machine the included benchmark shows a ~80% increase in throughput.
Note: This slightly changes some of the errors generated from object conversions since it no longer parses non-objects. Eg. `Joi.object().validate('"hello"')` now has `"hello"` in `err.context.value` instead of `hello`. I don't think this is an issue, and I suspect it is actually a bug fix.
**Background**
Throws are very expensive in v8, so it pays to avoid them whenever possible. This is done by screening the strings that are passed to `JSON.parse()` to avoid parsing strings that have no chance to parse into something we need.
The screening is done by a regex. Since this adds a …
=> Faster object/array conversion fails

test/types/object.js
Re: #1748 Passes validation options through to pattern validation to support context refs.
=> Pass options to pattern validation to support refs

lib/types/any/index.js
This commit seems to have broken something: https://github.com/hapijs/joi/issues/1714
Well. once 15.0.1 went out.
```
"strip" is not allowed
at internals.Alternatives.checkOptions (/mnt/project/node_modules/@hapi/joi/lib/types/any/index.js:105:19)
at internals.Alternatives._validateWithOptions (/mnt/project/node_modules/@hapi/joi/lib/types/any/index.js:758:18)
at internals.Alternatives.validate (/mnt/project/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
at type.validate (/mnt/project/lib/by-document/lookup.js:82:123)
at type.validate (/mnt/project/node_modules/@hapi/joi/lib/index.js:394:54)
at type._validate (/mnt/project/node_modules/@hapi/joi/lib/types/any/index.js:676:35)
at internals.Array._checkItems (/mnt/project/node_modules/@hapi/joi/lib/types/array/index.js:245:37)
at …
```
=> remove strip from defaults now that it has been removed

API.md, lib/index.js, test/index.js
Per discussion in #1722 
One note is that since `attempt`/`assert` leverage `error.annotate()`, the error message is messier 
than I think @sarneeh was hoping for. This was already the case for `attempt`/`assert` on objects, though, and allowing `abortEarly` through does add the additional field annotations as well as the additional `error.details`.
=> Allow validate options to be passed through assert/attempt #1722

API.md
For `16.x` compatibility, based on #1831.
=> Fix outdated use of Joi.func().ref()

API.md
The current documentation for 16.x states that `attempt` is an alias for `assert`, but this is not true, as they have differing returns values. As in, `attempt` has a return value.
This PR fixes the documentation, borrowing some from the older 15.x doc for `attempt`, and some from the 16.x doc for `assert`.
Side note: I use `attempt` frequently and was initially dismayed to read that its core behavior had changed, until I actually tested it and was pleasantly surprised to see it still returned a converted object.
=> documentation: fix entry for "attempt"

API.md
The example might be from an older version. I think there is no top-level `.conditional` available anymore and the example should use `.when` instead.
Feel free to merge or just close the PR.
Thank you so much for creating and maintaining joi! It is a .. pleasure to work with 😃
=> Update documentation regarding conditional vs when

lib/schemas.js, test/extend.js
Closes #2242
I am not sure if this is intended or not but Joi v15 or lower allows `_` in rule names, however, Joi v16 doesn't allow it.
This PR may be a sort of bug fix for backward compatibility.
=> Allow `_` in alias, arg, flag, modifier, override, rule, and term names

API.md
Ensure documentation example reflects that method valid() no longer takes arrays as a parameter.
=> Update API.md - valid() no longer takes arrays

API.md
@hueniverse removed most of `fails because` in 6182a9b13a74286bd5cfcef1481e1c3555569266, but this documentation item remained, and the output doesn't match the documented expected output.
I'm not absolutely certain about the goal. I picked `err.local.key` because it sort of matched the kinds of things used in the rest of the message. 
Things I considered:
* `code` (`number.min`)
* `flags` (not seriously)
* `messages` (not seriously)
* `path` (`foo`)
* `prefs` (not seriously)
* `state` (not seriously)
* `value` (not seriously)
* `message` (not seriously)
* `template` (not seriously)
* `local`
* `limit` (already used)
* `value` (already used)
* `label` (`foo`)
* `key` (`foo`)
There were three choices for `foo`, I picked one fairly randomly, using a `local` seemed like a reasonable choice. …
=> Update API.md - correct sample - fails because is gone

API.md
I'm creating this as a PR because it appears that I don't need to create an Issue for a documentation change.
Note: this does relate to an Issue / PR that I intend to make, but the changes here are different.
A string in computer programming is not usually described as being "larger" than another string. What is usually discussed is the *length* of the string, and the comparison operators for lengths are "longer" and "shorter".
=> Strings are longer/shorter

API.md
Corrects an example in the date.less() documentation which uses max in place of less.
=> Correct example in date.less documentation

API.md
I think that it's worth noting docs that `[Joi.number(), Joi.string()]` would for example cast `'1'` to `1`.
It is a bit counterintuitive (but perfectly valid) that `Joi.alternatives()` uses the first sub-schema, even though the second sub-schema could match without casting
I had at least 2 bugs with it in my project, I wish I had noticed this behavior earlier.
=> API.md - clarify casting behavior of Joi.alternatives

lib/schemas.js
Extending Joi to implement a custom `cast` was not working with the following error:
````
"cast" is not allowed
````
Internal validation of extensions was not validating the field.
Example:
````js
Joi.extend((joi) => {
return {
type: 'object',
base: joi.object(),
cast: {
string: {
from: (value) => value && typeof value === 'object',
to: (value) => JSON.stringify(value),
},
};
}
});
````
=> Add extension validation for "cast"

lib/types/string.js, test/types/string.js
Fix for https://github.com/sideway/joi/issues/2419
=> Support ISO8601 with hours timeshift only

lib/index.d.ts
IDE flagged render as an invalid property today. I know this is a temporary file, but hopefully helps others in the meantime.
=> Add render property to ReferenceOptions TS def

lib/index.d.ts
In 03adf22eb1f06c47d1583617093edee3a96b3873, support for RegExps passed to Extension.type were introduced (e.g. `type: /^s/`). However, the types were missing that change.
=> Add RegExp to the supported types for Extension.type

lib/index.d.ts
trying to do 
```
const xValidator: CustomValidator<string> = (value, helpers) => {
if (!value.startsWith('x')) {
return helpers.error('string.x')
}
return value
}
```
results in error
```
TS2322: Type '(value: string, helpers: CustomHelpers<any>) => string | ErrorReport' is not assignable to type 'CustomValidator<string>'.
```
=> CustomValidator return type adjusted in typescript

lib/index.d.ts
In typescript:
```ts
const schema = Joi.object().alter({
foo: (schema) => schema.keys() // error: Property 'keys' does not exist on type 'Schema'.
})
```
=> Fix type of schema passed to alter functions

lib/index.d.ts
I want to make Schema type generic in order to improve typing
- Change is seamless from a typescript point of view. It isn't breaking anything.
- Allows type inference from Joi types
Motivation comes from this issue :
https://github.com/arb/celebrate/issues/212
I know it is not directly related to Joi, but with this change it can allow any package using Joi to have better type inferences.
=> feat: Make Joi.Schema generic

lib/types/array.js, package.json, test/types/array.js
Fixes #2404 
This will ensure that, if any remaining ordered contains a default constraint, it will be pushed to the value array.
```JS
if (ordered._flags.hasOwnProperty('default')) {
value.push(ordered._flags.default);
}
```
also, i changed the name of `fillOrderedErrors` method to `checkRemainingOrdereds` for clarity, since it's now not only filling errors.
=> fix: defaults in ordered array are not filled

lib/index.d.ts
If you try to appends a strongly typed object schema
```ts
import Joi from 'joi'
type TSchema = {
a: Joi.StringSchema
b: Joi.NumberSchema
}
const schema = Joi.object<TSchema>({
a: Joi.string(),
b: Joi.number(),
})
const schemaExtended = schema.append({
c: Joi.boolean(),
})
```
it result in error
```
Argument of type '{ a: Joi.StringSchema; b: Joi.NumberSchema; c: Joi.BooleanSchema; }' is not assignable to parameter of type 'SchemaMap<TSchema>'.
Object literal may only specify known properties, and 'c' does not exist in type 'SchemaMap<TSchema>'.
```
I suggested a commit that would make possible to do that:
```ts
import Joi from 'joi'
type TSchema = {
a: Joi.StringSchema
b: Joi.NumberSchema
}
type TSchemaExtended = TSchema & {
c: Joi.BooleanSchema
}
const schema = Joi.object<TSchema>({
a: …
```
=> Appends the allowed object keys in typescript

lib/index.d.ts
This adds the missing `.conditional` options array type.
=> Add option array type to AlternativesSchema.conditional

API.md
This fixes some typos I encountered for `any.allow()` and `object.missing`.
=> Fix typos in any.allow() and object.missing

lib/index.d.ts
Fixes part of https://github.com/sideway/joi/issues/2622 with adding objectSchema's type check.
Type validation will check all properties on existence and correct schema.
Extra parameters don't cause errors and there are may be smth missing in the `ObjectPropertiesSchema` 
Usage: 
```typescript
interface ObjType {
firstName: string;
lastName: string;
nestedObject: {
middleName: string;
}
}
// no errors
Joi.object<ObjType, true>({
firstName: Joi.string(),
lastName: Joi.string(),
nestedObject: Joi.object<ObjType['nestedObject'], true>({
middleName: Joi.string()
})
})
// error -> 'lastName' is missing
Joi.object<ObjType, true>({
firstName: Joi.string(),
nestedObject: Joi.object<ObjType['nestedObject'], true>({
middleName: Joi.string()
})
})
// error -> 'lastName' has incorrect shema type …
```
=> Add object type guards schema

browser/package.json, browser/webpack.config.js, browser/webpack.mocha.js
Latest Webpack generated dist files no longer reference "window". Thus those
generated files are compatible with Web Workers.
Fixes https://github.com/sideway/joi/issues/2251
=> Fix Web Workers compatibility

API.md
Line 3298: from `#state` to `#validation-state`
Line 3298: add a full stop
=> Fix wrong validation state href in docs

lib/types/alternatives.js
...during failure of `any` and `all` match modes.
Also considered adding additional context to `one` match mode, but the limit of what could be expressed without putting requirements on schema authors is likely just the index of matching schemas. e.g
`{ message: 'value matched more that one schema', context: { matchedSchemaIndexes: [0, 3, 4] } }`
=> add subschema property validation failures to context

lib/types/string.js, test/types/string.js
=> fix: Joi.string().hostname() not returning errors for CIDR notation

lib/validator.js, test/validator.js
Fixes #2600
Fixes #2635
I'm not convinced it's such a good thing to add the label to the error message when users have full control over the error, shouldn't we leave this error alone no matter what the settings say?
=> Fix label elimination for externals

lib/index.d.ts
Since #2455 `prefs` are passed to `external` validation as second argument. However, typings had not been updated.
This pr fixes typings for external validation.
Closes #2605
=> Fix typings on any.external(): add helpers argument

lib/index.d.ts
Handle mapping of `DateSchema` validation types to Date when using `StrictSchemaValidation<T>`
For example:
```
type MyApi = {
foo: string;
bar: Date;
}
const schema = Joi.object<MyApi>({
Joi.object({
foo: Joi.string(),
// this is a typescript error in current codebase
bar: Joi.date(),
}
```
=> Add Date -> Joi.DateSchema map to ObjectPropertiesSchema<T>

lib/index.d.ts
improves typings for the `.validate` function so that if a type is passed when calling `.object()` it also makes its way to `.validate().value`
=> issue #2606: pass TSchema from ObjectSchema to .validate function

lib/types/number.js
Updated `multiple` rule with a better use of the remainder (`%`) operator to support decimal/float base
[Demo](https://codepen.io/MathijsvVelde/pen/MWowBZe?editors=0012)
=> Updated `multiple` rule to support decimal/float base

API.md
This PR corrects 3 typos in the [API docs](https://github.com/sideway/joi/blob/master/API.md), as follows:
***
"Names links are recommended for most use cases"
-->
"Named links are recommended for most use cases"
***
```
{
knownMisses: Array<string>, // Labels of all the missing values
unknownMisees: number // Count of missing values that didn't have a label
}
```
-->
```
{
knownMisses: Array<string>, // Labels of all the missing values
unknownMisses: number // Count of missing values that didn't have a label
}
```
***
```
{
unknownMisees: number // Count of missing values that didn't have a label
}
```
-->
```
{
unknownMisses: number // Count of missing values that didn't have a label
}
```
=> Fix typos in API.md ('Names links' -> 'Named links', 'unknownMisees' -> 'unknownMisses')

lib/index.js, test/index.js
- internals.assert was failing in detect empty strings as a message setting this same empty string as options parameter
=> Fix Joi issue #2746

lib/index.d.ts
`joi.attempt` can return a template type rather than `any`
Closes #2643
=> feat(d.ts): improve attempt return type

lib/index.d.ts, test/index.ts
Since `details` property of `ValidationError` interface is typed as `ValidationErrorItem[]` then I see no reason why `details` param of `ValidationError` constructor should be typed as `any`.
=> fix(d.ts)!: type details param of ValidationError constructor

lib/index.d.ts
Based the comment on the matching code change here: https://github.com/sideway/address/blob/master/src/domain.ts
=> feat(d.ts): Add type information for `maxDomainSegments` to `EmailOptions` and `DomainOptions` interfaces

lib/index.d.ts, test/index.ts
=> feat: change validateAsync return type to match options

lib/index.d.ts, test/index.ts
A strict nested object was previously typed as `ObjectSchema<StrictSchemaMap<T>>`, which meant that Joi expected a Joi schema of a Joi schema of an object (i.e., a schema definition for an object of Joi schema fields) - which doesn't make much sense. Instead, it should require a Joi schema of an object _or_ an object of Joi schema fields.
=> Allow sub-objects for TypeScript strict object schema

lib/index.d.ts, test/index.ts
The goal is to handle "complex" unions (unions that aren't merely subsets of a single primitive type) without interfering with simple enumerated-constant-style unions (such as `'development' | 'production' | 'test'`) or booleans.
Include updated test cases from #2850.
Fixes #2848
=> Try improving handling of unions

benchmarks/suite.js, lib/types/number.js, test/types/number.js
Fixes #2542.
Fixes #2672.
This method is borrowed from https://github.com/josdejong/lossless-json, big kudos to him!
=> fix: better unsafe check of exponential numbers

lib/index.d.ts
Both `boolean.falsy` and `boolean.truthy` support `null` values. I've added this to the TS types to reflect this logic.
=> Allow null values in BooleanSchema methods

.github/workflows/ci-module.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

package.json
- Upgrades for `@sideway/formula` to `3.0.1` for `CVE-2023-25166`
- This will help users who are getting dependabot alerts about this
=> Upgrade `@sideway/formula` to `3.0.1` for `CVE-2023-25166`

browser/webpack.config.js
It seems webpack left `?.` and `??` in the build, I think it may be too early for that.
=> fix: transpile optional chaining

lib/state.js, lib/validator.js, test/base.js, test/validator.js
Warnings and externals should not appear in results nor run if this is the result of the validation of a mismatch in an array or an alternative.
=> fix: do not trigger warnings and externals on arrays and alternatives mismatches

lib/state.js, lib/types/alternatives.js, lib/types/array.js, lib/validator.js
Snapshots were being constantly added without ever being removed, creating a leak.
=> fix: commit states to avoid memory leak

API.md, lib/index.d.ts, lib/types/string.js, test/index.ts, test/types/string.js
- Include support for `uuidv6`, `uuidv7` and `uuidv8` GUID versions
- Updated documentation to include additional versions
- Added test cases validating added uuid versions
Currently these are unofficial versions (see [New UUID Formats](https://uuid6.github.io/uuid6-ietf-draft/)), but already have adoption.
=> feat: support uuidv6, uuidv7 and uuidv8 guid types

lib/types/binary.js, test/types/binary.js
What?
This adds to binary type handler the ability to utilize node.JS's built in Buffer JSON encoding and appropriate tests for the functionality.
What issues does this address?
https://github.com/hapijs/joi/issues/2954
What can be improved?
Why?
As a part of a larger request, it is helpful to be able to pass a binary value over a larger JSON model. I ran into this recently when passing request handlers over an HTTP call initiating a browser session that then had an array of request replacements. It worked great for JS and CSS, but small images would fail to decode properly.
Available workarounds?
This can also be achieved via doing the following in with the schema:
```JavaScript
Joi.alternatives(
Joi.binary(),
Joi.object({
type: 'Buffer',
data: …
```
=> feat: support bindary buffer that has been JSON.parse(JSON.strinified())

lib/index.d.ts
This fixes the ability do have types like:
```typescript
type Photo = {
id: number,
caption: string,
content: Buffer
};
const schemaProps: SchemaMap<Photo, true> = {
id: Joi.number(),
caption: Joi.string(),
content: Joi.binary()
};
```
=> Associate Buffer with BinarySchema

lib/index.d.ts
This function already accepts to return its input, let's fix the type.
=> fix: allow any.error() return type to be ErrorReport[]

lib/template.js, test/template.js
Formula expects a `null` value in case of missing references, since we replace the reference resolver, we must behave like it.
Fixes #2974.
=> fix: missing template reference

lib/index.d.ts, test/index.ts
closes #2980
with different types
with `try`
with `conditional`
=> feat: Improve alternatives type

.github/workflows/ci-module.yml, lib/types/number.js, test/errors.js, test/types/number.js
Fixes #2962.
Comparison method borrowed and adapted from https://stackoverflow.com/questions/7037926/javascript-how-to-tell-if-one-number-is-a-multiple-of-another
=> fix: precision issue on number().multiple()

lib/index.d.ts
Closes:
- https://github.com/hapijs/joi/issues/2720
- https://github.com/hapijs/joi/issues/2941
This feature has always really been supported, but the type was correct all the time, resulting in build errors.
Only fixable with ugly `ts-expect-error` patterns or `ts-patch` files.
It was really annoying to see this feature actually [documented](https://joi.dev/api/?v=17.9.1#anyvalidatevalue-options), but the type not being correct.
Multiple tests are already present, but this is one example:
https://github.com/hapijs/joi/blob/master/test/errors.js#L176-L196
Code that backs this up as being an existing and supported feature:
https://github.com/hapijs/joi/blob/master/lib/errors.js#L133-L143
Would love to hear back!
=> fix: LanguageMessages type now supports languages in TypeScript

lib/types/alternatives.js, test/types/alternatives.js
When using labels on underlying schemas of labeled Joi.alternatives, the Joi.alternatives' label overwrites the labels of the underlying schemas. I think this is a bug and therefore propose the changes in this PR.
Based on reading existing tests, I assume passing labels from Joi.alternatives to underlying schemas is wanted, though I do not believe this should be the case when the underlying schemas already have their own labels. The fact that I am not breaking any existing tests with these changes further reinforces my belief that this may be a bug. I only added a few new tests to cover the behavior introduced in my changes.
In my project, I am using joi-to-swagger to convert Joi schemas to OpenAPI-compatible schemas. In case of Joi.alternatives, this leads to `anyof` or `oneOf` (meaning …
=> fix: do not override existing labels of underlying schemas in alternatives

lib/types/string.js, test/types/string.js
Closes #2386
This PR updates the regex for validating hexadecimal. This allows hexes with the `0x` prefix to be validated properly and those without to also pass validation provided they're valid hex strings.
=> Allow 0x prefix for hex strings

API.md, lib/index.d.ts, lib/types/string.js, test/types/string.js
Backport #3011 and changes the options.
=> feat: hex prefix

lib/types/array.js, test/types/array.js
When trying to validate uniqueness on bigint type arrays, the error `Failed to find unique map container for type bigint` is returned.
this PR adds handling bigint as a native type without having to provide a compare function and treat it as custom
=> fix: handle bigint in unique rule

API.md, lib/index.d.ts, lib/types/string.js, test/types/string.js
- #2889 
- Added optional field `encodeUri` with default `false` in `UriOptions`.
- Added `encodeUri` in string validation method.
- Returns encoded URI when both `convert` and `encodeUri` flags are `true`.
- Added a test case to reproduce the issue.
=> feat: Support encoding uri

lib/types/keys.js, test/index.js
When explicitly specifying `.unknown(false)`, running validations with `stripUnknown: true` should respect the local override.
=> fix: `stripUnknown` should honor local explicit `.unknown(false)`

lib/index.d.ts
Currently the [comments describing boolean()](https://github.com/hapijs/joi/blob/3cb73d6cded39fa49a46069b64d638a0ba0f7d14/lib/index.d.ts#L2094) advise that 'true', false', 'yes', or 'no' will be automatically handled if not in strict() mode, however for some time the actual default behaviour has been only to convert 'true' and 'false' (since around [v10](https://github.com/hapijs/joi/commit/b14693f92fc1c3a761befbd19462c0c843194589) I think).
Just a very small PR to fix them up
=> Minor correction for boolean() documentation

API.md, lib/index.d.ts
Fixes #3053
This adds additional details to the documentation for `.empty()`.
Specifically, it:
- Notes that calls to `.empty()` override any prior calls.
- Clarifies that `schema` may also be a raw value or an array of matches.
=> Clarify documentation for empty()

lib/base.js, lib/index.d.ts, lib/validator.js, package.json, test/base.js, test/helper.js, test/index.ts, test/validator.js
Implements standard-schema.
Fixes #3078
=> feat: implement standard schema spec
